apiVersion: v1
name: cubestore
description: A Helm chart for Cubestore
type: application
version: 0.1.1
appVersion: "0.28.32"
keywords:
  - cubejs
  - cubestore
maintainers:
  - email: luc.vauvillier@gmail.com
    name: Luc Vauvillier
sources:
  - https://github.com/cube-js/cube.js
