apiVersion: v1
kind: Service
metadata:
  name: crm-api
  namespace: {{ include "crm-api.namespace" . }}
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  crm-api-service_mapping{{ if ne (include "crm-api.namespace" .) "default" }}-{{ include "crm-api.namespace" . }}{{ end }}
      prefix: /crm-api/
      service: crm-api
      timeout_ms: 300000
spec:
  selector:
    app: crm-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: grpc
      port: 1337
      targetPort: 1337
