{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ft-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ft-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecret.target.name | default (include "ft-service.fullname" .) }}
    creationPolicy: Owner
    {{- with .Values.externalSecret.target.template }}
    template:
      engine: v2
      {{- toYaml . | nindent 6 }}
    {{- end }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- with .property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
{{- end -}}
